### PR TITLE
AreWavesEqual creates better message for wave data check

### LINKED ISSUE #30: Easier out of the box debugging for failed test assertion `*_EQUAL*WAVES`
I just had a failed test with the following JUNIT output:

```
FAIL: Assuming equality using mode 033 for waves guiStateNumRef and guiStateNumNew: is false   Assertion "CHECK_EQUAL_WAVES(guiStateNumRef, guiStateNumNew, mode = WAVE_DATA | DIMENSION_LABELS)" failed in line 230, procedure "UTF_DAEphys.ipf" 
```

and I had to do the following to debug it:
- Rerun the test with `keepDataFolder=1` so that I get access to the waves
- Duplicate the waves and diff them manually
- call `WaveStats` to find the first non-matching entry

This is quite tedious to do manually.

Outputting this kind of info always would be really helpful.

- Output the first non-matching entry together with wave indizes and dimension labels
- Use tolerance correctly
- Investigate if it is feasable to support all modes or only `WAVE_DATA`

### PR DESCRIPTION
**Pull request by MathiasAugstein**
When the data in two waves differ, AreWavesEqual now gives information
where the first and the last difference occured.
FindDifferentWaveEntries, GetWaveIndexInfo and GetWaveDimension funtions
were added in order to work.

Remark: In FindDifferentWaveEntries the built-in function FindLevel was not used, as it returns NAN if already the first element is above the tolerance, or if no element is above the tolerance. That would require an additional step, even though it would be simple if we can assume the second case is impossible because the waves are not equal.

Closes #30

### CODE REVIEW

**Comment by MathiasAugstein** [comment]
Very early stage, there is no more time for big improvements. Might be finished later.

**Comment by MathiasAugstein** [comment]
Changes were made, now it should work with all types of waves and handle data differences correctly.

As discussed on phone this was intended to be a first version with the main highlight on correct execution. There is a lot of code duplication in the functions for each wave type (e.g. `FindDifferentWaveEntryNumeric`), it should be possible to transfer the 4 loops inside `FindDifferentWaveEntry` and call the corresponding wave-specific functions inside the loops.

**Comment by MichaelHuth** [comment]
Current output design:
```
  Text wave differences:
Dimensions              |DimLabels |Wave Name  |Text          |
------------------------|----------|-----------|--------------|
    0;    0;    0;    0;|LABEL1;;;;|wa in root:|Der eine Text |
                        |LABEL3;;;;|wb in root:|Der andre Text|
    1;    0;    0;    0;|LABEL2;;;;|wa in root:|mehr Text     |
                        |LABEL4;;;;|wb in root:|viel mehr Text|
```

**Comment by t-b** [comment]
That looks like a good start.

**Comment by MichaelHuth** [comment]
@t-b How should we handle the latest IP9 changes regarding the printout? Is there some outlook that a %p format code will be available?

**Comment by t-b** [comment]
> @t-b How should we handle the latest IP9 changes regarding the printout? Is there some outlook that a %p format code will be available?

I'm investigating.

**Comment by t-b** [comment]
@MichaelHuth Could you add some examples to internal_dev?

And I'm also not seeing a detailed message for the following test case:

```
Function Test()

	CHECK_EQUAL_WAVES({1}, {2})
End
```

**Comment by MichaelHuth** [comment]
Hmm I get as JUnit:

```xml
<?xml version="1.0" encoding="utf-8"?>
<testsuites>
	<testsuite package="Procedure" id="0" name="Procedure" timestamp="2021-03-04T02:00:06" hostname="DESKTOP-H4EJ6SM" tests="1" failures="1" errors="0" skipped="0" disabled="0" time="0.014">
		<properties>
			<property name="User" value="Micha"/>
			<property name="System" value="OS:Windows 10 Pro;
OSVERSION:6.3.18363;
LOCALE:US;
IGORFILEVERSION:9.0.0.3"/>
			<property name="Experiment" value="deleteme"/>
			<property name="UTFversion" value="1.08"/>
			<property name="IgorInfo" value="IGORVERS:9.00;
BUILD:36995;
IGORKIND:pro64;
FREEMEM:140731578343424;
PHYSMEM:68607193088;
USEDPHYSMEM:653590528;
NSCREENS:1;
SCREEN1:DEPTH=32,RECT=0,0,3840,2160"/>
		</properties>
		<testcase name="mytest in Procedure (50)" classname="mytest" time="0.008">
			<failure message="Assuming equality using mode WAVE_DATA for waves _free_ and _free_; detailed: Waves difference:
Wave1:0x084767a370
Wave2:0x084767a710
Dimensions  |Labels|Value   |
------------|------|--------|
[0][0][0][0]|      |1.000000|
            |      |2.000000|

: is false.  Assertion &quot;CHECK_EQUAL_WAVES({1}, {2})&quot; failed in line 3, procedure &quot;Procedure&quot;" type="FAIL"></failure>
		<system-out>Entering test case &quot;mytest&quot;
Assuming equality using mode WAVE_DATA for waves _free_ and _free_; detailed: Waves difference:
Wave1:0x084767a370
Wave2:0x084767a710
Dimensions  |Labels|Value   |
------------|------|--------|
[0][0][0][0]|      |1.000000|
|      |2.000000|

: is false.  Assertion &quot;CHECK_EQUAL_WAVES({1}, {2})&quot; failed in line 3, procedure &quot;Procedure&quot;
Leaving test case &quot;mytest&quot;
</system-out>
		<system-err>Assuming equality using mode WAVE_DATA for waves _free_ and _free_; detailed: Waves difference:
Wave1:0x084767a370
Wave2:0x084767a710
Dimensions  |Labels|Value   |
------------|------|--------|
[0][0][0][0]|      |1.000000|
            |      |2.000000|

: is false.  Assertion &quot;CHECK_EQUAL_WAVES({1}, {2})&quot; failed in line 3, procedure &quot;Procedure&quot;</system-err>
		</testcase>
		<system-out>Entering test case &quot;mytest&quot;
Assuming equality using mode WAVE_DATA for waves _free_ and _free_; detailed: Waves difference:
Wave1:0x084767a370
Wave2:0x084767a710
Dimensions  |Labels|Value   |
------------|------|--------|
[0][0][0][0]|      |1.000000|
|      |2.000000|

: is false.  Assertion &quot;CHECK_EQUAL_WAVES({1}, {2})&quot; failed in line 3, procedure &quot;Procedure&quot;
Leaving test case &quot;mytest&quot;
</system-out>
		<system-err>Assuming equality using mode WAVE_DATA for waves _free_ and _free_; detailed: Waves difference:
Wave1:0x084767a370
Wave2:0x084767a710
Dimensions  |Labels|Value   |
------------|------|--------|
[0][0][0][0]|      |1.000000|
            |      |2.000000|

: is false.  Assertion &quot;CHECK_EQUAL_WAVES({1}, {2})&quot; failed in line 3, procedure &quot;Procedure&quot;</system-err>
	</testsuite>
</testsuites>

```

looks solid to me.

**Comment by t-b** [comment]
Jeep, thanks. That error was on my side.

**Comment by MichaelHuth** [comment]
Rebased and with examples

**Review by t-b — CHANGES_REQUESTED** [review]
Code works as expected!

Some output issues:
- Can the dimension sizes and type table, EqualWavesSizes() EqualWavesType*(), have the same format as for different
  data? Basically I want to have the same layout always.
  Including the wave names before the table?
- Add a space after ":" in "Wave1:..."

Code issues:
- Does not compile on IP6
- Other CI failures
- Please use the WAVEYTPE0_XXX/WAVEYTPE1_XXX constants you introduced over magic numbers
- Prefer i, j, k, l as outlined in the coding guidelines for loops variables
- "TODO only IP7" should be fixed or?
- "convert 32 bit int or less to double without precision loss" I'm not understanding that. I thought we mimick the IP behaviour regarding 64bit integers? I. e. casting them down to double?

Edgy edge cases:

The following example (please add it)

```igorpro
Function EqualWavesTextWithNulls()

	string str1, str2
	
	str1 = "abcd"
	str2 = PadString(str1, strlen(str1) + 1, 0x0)

	CHECK_EQUAL_TEXTWAVES({str1}, {str2}, mode=WAVE_DATA)
End
```

gives

```
  Start of test "Unnamed"
  Entering test suite "EqualWaves_Examples.ipf"
  Entering test case "EqualWavesTextWithNulls"
  Assuming equality using mode WAVE_DATA for waves _free_ and _free_; detailed: Text waves difference:
Wave1:0x0857edab0
Wave2:0x0857ed3d0
Dimensions  |Labels|Text|
------------|------|----|
[0][0][0][0]|      |abcd|
            |      |abcd|

: is false.  Assertion "CHECK_EQUAL_TEXTWAVES({str1}, {str2}, mode=WAVE_DATA)" failed in line 16, procedure "EqualWaves_Examples.ipf"
  Leaving test case "EqualWavesTextWithNulls"
  Failed with 1 errors
  Leaving test suite "EqualWaves_Examples.ipf"
  Test finished with 1 errors
  End of test "Unnamed"
```

and makes the reader wonder what is different. Is there an easy way to solve that? Another column with the string lengths?

**Comment by MichaelHuth** [comment]
Regarding the edgy case: The general issue is that strings can contain non-printable characters that can make a difference.
Printing the string length would add an indication but its not very reliable as the strings might even have the same length.
The only reliable way I would think of is:
If the string contains non-printable characters then add a hex code representation because the comparison itself is binary and not UTF-8 character based.

**Comment by t-b** [comment]
Am Donnerstag, den 04.03.2021, 13:31 -0800 schrieb Michael Huth:

[...]

> The only reliable way I would think of is:
> If the string contains non-printable characters then add a hex code
> representation because the comparison itself is binary and not UTF-8
> character based.

Sounds like a good idea!

**Comment by MichaelHuth** [comment]
ok,

regarding the last point in Code Issues: This was indeed a leftover from the state where the code had a separate part for INT64.
Though I noticed that my former local tests for INT64 were not correctly setup. As a result I had to reinclude parts for INT64 handling. Also the INT64 value printout was incorrect for unsigned and is still incorrect for complex values.
The problem with the latter is that only wfprintf supports printing complex wave elements but it converts to double before. This is reported, but I don't see a working option at the moment. Getting the component values by real() and imag() also converts to double.

**Comment by t-b** [comment]
> The problem with the latter is that only wfprintf supports printing complex wave elements but it converts to double before. This is reported, but I don't see a working option at the moment. Getting the component values by real() and imag() also converts to double.

If IP does not have an option here, we need to live with it right? Just be sure to document the issue in our IP issue list.

**Comment by t-b** [comment]
So the elements we can't printout properly are complex int64 wave elements? I'm fine with having that as a known limitation.

**Comment by MichaelHuth** [comment]
In addition to the code issues the following is fixed:
- fixed incorrectly working comparison of 64 bit integer and complex 64 bit integer values (including tolerance).
- added UTF-8 character parser for extended output of strings

**Comment by t-b** [comment]
-  [ ] Merge conflict
- [ ] Does that run without RTE on your side on latest IP9? Here I get a lot of RTEs.

**Comment by MichaelHuth** [comment]
Also fixed the RTEs in IP6 and related possible RTEs in IP7/8 due to possible too long output strings with the EqualWaves table.

**Review by t-b — APPROVED** [review]
Very nice!

**Pull request merged**
