### PR TITLE
pre-commit: Add basic configuration

### LINKED ISSUE #280: Think about adding basic code style CI
In MIES we have https://github.com/AllenInstitute/MIES/blob/main/tools/check-code.sh which checks for common issues with code and some IP code checks.

We could leverage something like this here as well to avoid common PR reponses (No space after if, etc.).

One could also use a more structured approach via e.g. https://github.com/pre-commit/pre-commit. Thoughts?

### PR DESCRIPTION
**Pull request by t-b**
- [x] Add pre-commit==2.20.0 to docker-utils image and remove from .gitlab-ci.yml
- [x] Discuss hooks with @MichaelHuth and @Garados007 

Close #280

### CODE REVIEW

**Comment by t-b** [comment]
https://gitlab.byte-physics.de:4001/mirror/igor-unit-testing-framework/-/jobs/55909 has the output.

**Review by Garados007 — CHANGES_REQUESTED** [review]
1. I think there should be merge problems with the current state of the main branch. 9f1d61149d66eab9eb68be2b0787e94b9b645ec7 (Fix whitespace issues, 2022-11-01) has solved most of the existing whitespace issues.
2. Can we add `--show-diff-on-failure`? This would help us finding the problems faster.
3. In the commit message a33fa5340f5f04f3fcaae5242b2488d31ec1e6bc (Fix common whitepace issues) you are telling me you have removed the trailing new line at the end of the file. You are clearly adding them back in the commit.
4. In 7eff5c1740e38277db468d42cd2467f77ac6f748 (docu/scripts: Nicify whitespace) the commit message is unspecific. Can you be more specific like "Add newline after shebang"?
5. In 2123cef086b8a59ada5e3d47fc6be005fa39dca3 (docu/scripts: Fix shebang) you are also adding new lines after the shebang. Maybe it would be more wise to combine 7eff5c1740e38277db468d42cd2467f77ac6f748 (docu/scripts: Nicify whitespace) and 2123cef086b8a59ada5e3d47fc6be005fa39dca3 (docu/scripts: Fix shebang).
6. I think it would be better if you switch the order of 0b9adcdd05e8fd316cdc09404b9e30749ee6a3ce (.gitlab-ci.yml: Add pre-commit CI job) and ed0b54bdb7a5856a6dbbad8cea945ebf0cc635a5 (pre-commit: Add basic configuration). In the current state you are adding the job to the pipeline and adding the configuration after that. The other way round would be more understandable.

**Comment by Garados007** [comment]
I just saw that I wasn't assigned that at all. Well, never mind.

**Comment by t-b** [comment]
> I think there should be merge problems with the current state of the main branch. https://github.com/byte-physics/igor-unit-testing-framework/commit/9f1d61149d66eab9eb68be2b0787e94b9b645ec7 (Fix whitespace issues, 2022-11-01) has solved most of the existing whitespace issues.

I've rebased and yes the trailing whitespaces issues are mostly gone.

> Can we add --show-diff-on-failure? This would help us finding the problems faster.

Good idea.

> In the commit message https://github.com/byte-physics/igor-unit-testing-framework/commit/a33fa5340f5f04f3fcaae5242b2488d31ec1e6bc (Fix common whitepace issues) you are telling me you have removed the trailing new line at the end of the file. You are clearly adding them back in the commit.

I've reworded the commit message.

> In https://github.com/byte-physics/igor-unit-testing-framework/commit/7eff5c1740e38277db468d42cd2467f77ac6f748 (docu/scripts: Nicify whitespace) the commit message is unspecific. Can you be more specific like "Add newline after shebang"?

Done.

> In https://github.com/byte-physics/igor-unit-testing-framework/commit/2123cef086b8a59ada5e3d47fc6be005fa39dca3 (docu/scripts: Fix shebang) you are also adding new lines after the shebang. Maybe it would be more wise to combine https://github.com/byte-physics/igor-unit-testing-framework/commit/7eff5c1740e38277db468d42cd2467f77ac6f748 (docu/scripts: Nicify whitespace) and https://github.com/byte-physics/igor-unit-testing-framework/commit/2123cef086b8a59ada5e3d47fc6be005fa39dca3 (docu/scripts: Fix shebang).

Yeep, that was sloppy.

**Review by Garados007 — APPROVED** [review]
This is a good starting point which can be extended in the future. LGTM.

**Review by MichaelHuth — APPROVED** [review]
LGTM

**Pull request merged**
