### PR TITLE
Bugfix/erroneous junit output

### LINKED ISSUE #51: JUNIT output does not hold proper info for RTEs in user hooks
```
Function TEST_SUITE_END_OVERRIDE(str)
	string str

	ABort 

End

Function Dostuff()

	PASS()
End
```

gives in IP

```
•runtest("procedure", enableJU=1)
  Start of test "Unnamed"
  Entering test suite "Procedure"
  Entering test case "Dostuff"
  Leaving test case "Dostuff"
  Encountered "Abort" in user hook "TEST_SUITE_END_OVERRIDE", procedure file "Procedure"
  Test finished with no errors
  End of test "Unnamed"
```

but

in the XML

```
<?xml version="1.0" encoding="utf-8"?>
<testsuites>
</testsuites>
```

### PR DESCRIPTION
**Pull request by t-b**
Close #51.

### CODE REVIEW

**Comment by MichaelHuth** [comment]
ClearRTError should be static.

**Comment by t-b** [comment]
@MichaelHuth Good point. Fixed.

**Comment by MichaelHuth** [comment]
I find it a bit misleading that for TEST_BEGIN_OVERRIDE and TEST_END_OVERRIDE the origin is a "Undefined Procedure" procedure file.

This originates from unit-testing-basics line 1369 and line 1382 where the string is given as default.

**Comment by MichaelHuth** [comment]
Please include
`#include "unit-testing"`
in aborting-user-hooks.ipf

**Comment by t-b** [comment]
@MichaelHuth Alternative suggestions for "Undefined Procedure"?

**Comment by t-b** [comment]
@MichaelHuth I've done the include change. This was formerly added into the builtin procedure.

**Comment by t-b** [comment]
@MichaelHuth I've used "No source procedure" now.

**Pull request merged**
