### PR TITLE
Make string comparisons always case sensitive by default

### LINKED ISSUE #291: Make the default for string matching case-sensitive.
For waves comparison the string matching is always case-sensitive and byte-wise for Igor >= 7.05. For CHECK_EQUAL_STR the default for string matching is case-insensitive which is not intuitive.

In my opinion we should change it to case-sensitive (with the option for case-insensitive matching) for all string checks because in a test case we are expecting exact data and we are not working with user input.

### PR DESCRIPTION
**Pull request by t-b**
- [x] Add VTTE test which tests the *default* value for case_sensitive.

Close #291

### CODE REVIEW

**Comment by t-b** [comment]
We've got 4 assertion failures in MIES which has 1332 testcases. So I'd say we can flip the default.

**Comment by Garados007** [comment]
4 failures? I thought there would be way more.

I support this PR and LGTM!

**Review by Garados007 — APPROVED** [review]

**Review by MichaelHuth — CHANGES_REQUESTED** [review]
Code wise thats ok. But I think in the commit message the last sentence should refer to flipping the default in EQUAL_STR_WRAPPER and not EQUAL_WAVE_WRAPPER ?

**Comment by t-b** [comment]
@MichaelHuth Good point. Fixed.

Here is the range diff:
```
$ git range-diff @{u}...HEAD
1:  3274264 ! 1:  89c28de EQUAL_STR_WRAPPER: Make the default case sensitive
    @@ Commit message

         We can't flip the case sensitivity switch for EqualWaves as there is none.
         And a testing framework should also be as strict as possible, so we flip
    -    the default for EQUAL_WAVE_WRAPPER to case sensitive.
    +    the default for EQUAL_STR_WRAPPER to case sensitive.

         Reported-by: @Garados007
         Test-code-by: @Garados007
```

**Pull request merged**
