### PR TITLE
Equal waves fixes

### LINKED ISSUE #42: Add Workaround for EqualWaves bug in *_EQUAL_WAVES
Versions of IP8 below 33418 and IP7 before 12th march 2019 can under some circumstances create waves which have equal dimension labels when compared naivly but `EqualWaves(wv1, wv2, DIMENSION_LABELS)` returns 0.

Work around that issue for the case of EqualWaves failure.

### LINKED ISSUE #43: *_EQUAL_WAVES: EqualWaves returns NaN for unknown modes
- Rewrite all code like `if(!result)` to `if(result == 0)` to avoid issues with NaN

### PR DESCRIPTION
**Pull request by t-b**
Close #42.
Close #43.

### CODE REVIEW

**Comment by MichaelHuth** [comment]
It is not connected to the DimLabel patch, but I find the following code failing unexpected:

```
	Make/N=0 w1
	WAVE w2=w1

	CHECK_EQUAL_WAVES(w1,w2)
```

**Comment by MichaelHuth** [comment]
@t-b I think you miss the UTF8 normalization before comparing the labels, as this fails:

```
	Make/N=2 w1,w2
	
	string s1 = U+0301 + U+0065
	string s2 = U+00e9
	
	SetDimLabel 0,1,$s1, w2
	SetDimLabel 0,1,$s2, w1

	CHECK_EQUAL_WAVES(w1,w2)
```

Both labels are canonically equivalent.

**Comment by t-b** [comment]
Thanks for the review. I'll look into it.

**Comment by t-b** [comment]
@MichaelHuth Igor never does unicode normalization.

```
Function DoStuff()
	Make/N=2 w1,w2

	string s1 = U+0301 + U+0065
	string s2 = U+00e9

	SetDimLabel 0,1,$s1, w2
	SetDimLabel 0,1,$s2, w1

	CHECK_EQUAL_WAVES(w1,w2, mode = DIMENSION_LABELS)

	print cmpstr(s1, s2)
	CHECK_EQUAL_STR(s1, s2)
End
```

gives 

```
•runtest("procedure", allowdebug=1)
  Start of test "Unnamed"
  Entering test suite "Procedure"
  Entering test case "DoStuff"
  Assuming equality using mode 032 for waves w1 and w2: is false
  Assertion "CHECK_EQUAL_WAVES(w1,w2, mode = DIMENSION_LABELS)" failed in line 21, procedure "Procedure"
  1
  "́e" == "é" not respecting case: is false
  Assertion "CHECK_EQUAL_STR(s1, s2)" failed in line 24, procedure "Procedure"
  Leaving test case "DoStuff"
  Failed with 2 errors
  Leaving test suite "Procedure"
  Test finished with 2 errors
  End of test "Unnamed"
```

So I'm not sure that this is really the right point to start it.

**Pull request merged**
