### PR TITLE
Support macros in instrumentation

### PR DESCRIPTION
**Pull request by MichaelHuth**
Changes to support also Macros in instrumentation.

close https://github.com/byte-physics/igor-unit-testing-framework/issues/234

### CODE REVIEW

**Comment by MichaelHuth** [comment]
@t-b I could use some information from the CI machine. Currently the tests on Various.pxp time out. If the job times out no screenshot is generated. The Various.pxp test works here locally.

**Comment by t-b** [comment]
@MichaelHuth 
grafik

**Comment by MichaelHuth** [comment]
@t-b ok, the cause was that this line already relies on the auto-indexing skip on zero size patch in the recent nightlies of IP9. Thus, with the nightly this worked out of the box.

**Review by t-b — APPROVED** [review]
Very nice!

**Review by t-b — APPROVED** [review]

**Pull request merged**
