### PR TITLE
Add new multi multi data test cases with multiple input variables

### PR DESCRIPTION
**Pull request by MichaelHuth**
Adds Multi-Multi data test cases

close https://github.com/byte-physics/igor-unit-testing-framework/issues/213
close https://github.com/byte-physics/igor-unit-testing-framework/issues/158

### CODE REVIEW

**Comment by t-b** [comment]
Review: 
da3fa091 (Add structure and test case prototype function for multi-multi-data tests, 2022-09-08)

Jeep.

f9c54c45 (Adapt tagWave creation to store mmData generator tags with unique dimLabel, 2022-09-08)

Hmm.

77bbfc7f (Add data generator function validity check for mmData Generators, 2022-09-09)

```
+    FUNCREF TEST_CASE_PROTO_MD fTCmmd = $fullFuncName
+    if(UTF_FuncRefIsAssigned(FuncRefInfo(fTCmmd)))
+        dgenList = CheckFunctionSignatureMDgen(procWin, fullFuncName)
+        return 0
+    endif
+
```

Newline before this block.

Note to self: CheckFunctionSignatureTC now aborts with an empty generator wave.

62021e62 (Added constants for mode for multi data test cases, 2022-09-09)

Nice find.

9cbaa389 (Add MMD TestCase setup and Call, 2022-09-09)

Does GetMMDataState store GetMMDFuncState waves? If yes the documentation should say so.

ea31c6d9 (Add test case suffix for MMD test cases, 2022-09-09)

```
+        if(index < genSize)
+            mdFunState[i][%INDEX] = num2istr(index)
+            break
+        else
+            mdFunState[i][%INDEX] = num2istr(0)
+        endif
+    endfor
+
+    return i == numVars
+
```

That is difficult to follow. How about

```
for(...)
  [...]
  if(index < genSize)
    mdFunState[i][%INDEX] = num2istr(index)
    return 0
  endif

  mdFunState[i][%INDEX] = num2istr(0)
endfor

  return 1
End
```

instead?

58d91183 (Introduce StrConstant for test case suffix separator, 2022-09-09)

Okay.

5a181942 (Change GetFunctionTagWave to allow upto numLines tags, 2022-09-09)

Nice.

5ffaab41 (Call data generator only once for MMD test cases, 2022-09-09)

Yes!

4e78d987 (Check MMDataGen tags for correct variable names, 2022-09-12)

```
+                testRunData[tdIndex][%TAP_SKIP] = num2istr(TAP_IsFunctionSkip(fullFuncName) | markSkip)
```

Logical or instead for clarity?

c0ee0ce9 (Mark TC with zero sized data generator for SKIP, 2022-09-12)

Juup.

8e9bd0e9 (Rename Dimlabel of TestRunData from TAP_SKIP to SKIP, 2022-09-12)


Unrelated change:

```
-            ExecuteHooks(TEST_SUITE_BEGIN_CONST, s.procHooks, s.juProps, procWin, procWin)
+            ExecuteHooks(TEST_SUITE_BEGIN_CONST, s.procHooks, s.juProps, procWin, procWin, s.i)
```

6e21fedc (Count test suite numbers correctly for JUNIT output, 2022-09-12)

Nice find!

3b11806a (Evaluate SKIP in junit as skipped test case, 2022-09-12)

Good!

b9146587 (Replace tap_caseCount with loop index, move into ExecuteHooks function, 2022-09-12)

+1

35c81385 (Determine previousProcwin locally from previous TestRunData index, 2022-09-12)

Should be part of #262 and squashed into the commit introducing previousProcWin.

6e230e8b (Prefer s.i over i in index variable usage in main loop, 2022-09-12)

Okay.

7bda0d56 (Fix: Abort check after MD TC loop was missing, 2022-09-12)

Should be part of #262 and squashed into the commit introducing the bug.

14886829 (Rename tap_skipCase to skip, 2022-09-12)

Should be part of 3b11806a.

9b886b23 (Fix: get wGenerator reference correctly after reentry for tcSuffix, 2022-09-12)

Please squash that into the commit introducing the bug.

7815869b (Add tests for Multi-Multi-Data Test Cases, 2022-09-09)

Can you add these tests to Various.ipf? I would like to reserve VTTE.ipf for test assertion checks.
And can you also verify that the data generator functions are only called once?

3e6a37dd (Add documentation for new feature and changed behavior, 2022-09-12)

```
+If the TAP directive to skip a test case was placed then the test case is also
+treated to be skipped when JUNIT is enabled.
```

I think this not desired but can be presuaded otherwise.


```
+       int64 i3
+      int64 i4
+   EndStructure
+
```

Wrong indentation.


```
+If Multi-Multi-Data test cases are combined with functions with background activity the reentry function must have the same
+declaration.
+
```

declaration -> signature.


```
change fastest
```

-> changes

**Review by t-b — CHANGES_REQUESTED** [review]
See comment.

**Comment by t-b** [comment]
I think this PR also closes #158.

**Comment by MichaelHuth** [comment]
> Logical or instead for clarity?

I think a boolean OR is correct here because effectively TAP_IsFunctionSkip() returns a boolean and markSkip is also a boolean and both boolean flags are of the same type "skip".
Should we have some recommendation in the coding convention when to prefer logical ORs?

**Review by t-b — APPROVED** [review]

**Comment by t-b** [comment]
LGMT.

**Pull request merged**
